version: '3.8'

services:
  adapter:
    profiles:
      - base

  agent:
    # try out agent2.0
    # image: ladder99/agent2:latest
    profiles:
      - base
    ports:
      - '5000:5000'
    labels:
      - traefik.enable=true
      - traefik.http.routers.agent.rule=Host(`demo-north-agent.ladder99.com`)
      - traefik.http.routers.agent.tls=true
      - traefik.http.routers.agent.tls.certresolver=lets-encrypt
      - traefik.port=5000

  # cloudbeaver:
  #   profiles:
  #     - base
  #   image: dbeaver/cloudbeaver:21.3.5 # use this for x86 etc
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.cloudbeaver.rule=Host(`demo-north-beaver.ladder99.com`)
  #     - traefik.http.routers.cloudbeaver.tls=true
  #     - traefik.http.routers.cloudbeaver.tls.certresolver=lets-encrypt
  #     - traefik.port=8978

  dozzle:
    profiles:
      - base

  # note: must set owner of folders with
  #   sudo chown -R 0:0 ../client-mazak/volumes/grafana
  grafana:
    profiles:
      - base
    #. can you set grafana_port to nothing?
    ports:
      - '$GRAFANA_PORT:3000/tcp'
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`demo-north.ladder99.com`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=lets-encrypt
      - traefik.port=3000

  # hue:
  #   profiles:
  #     - base
  #   dns: 8.8.8.8
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.hue.rule=Host(`demo-north-beaver.ladder99.com`)
  #     - traefik.http.routers.hue.tls=true
  #     - traefik.http.routers.hue.tls.certresolver=lets-encrypt
  #     - traefik.port=8888

  pgadmin:
    profiles:
      - base
    dns: 8.8.8.8 # ? from hue?
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`demo-north-beaver.ladder99.com`)
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=lets-encrypt
      - traefik.port=8888 # ? from hue? should be 5050?

  portainer:
    profiles:
      - base

  postgres:
    profiles:
      - base

  relay:
    profiles:
      - base

  # this must be turned off when running locally on windows!
  # hence setting it to prod profile.
  traefik:
    profiles:
      - prod
